//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using BDSA.ReviewIt.Server.Logic.Utilities.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Server.Controllers
{
    [Route("api/[controller]")]
    public class ExportController : Controller
    {
        private readonly IExportLogic _exportLogic;

        public ExportController(IExportLogic exportLogic)
        {
            _exportLogic = exportLogic;
        }

        /// <summary>
        /// Exports study by id
        /// </summary>
        /// <param name="id"></param>
        /// <returns> IActionResult </returns>
        [HttpGet("/study/{id}")]
        public async Task<IActionResult> Export(int id)
        {
            var export = await _exportLogic.ExportStudy(id);

            if (export == null)
            {
                return NotFound();
            }

            return Ok(export);
        }

    }
}

