//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using BDSA.ReviewIt.Server.Logic.Utilities.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Server.Controllers
{
    [Route("api/[controller]")]
    public class ImportController : Controller
    {
        private readonly IImportLogic _importLogic;

        public ImportController(IImportLogic importLogic)
        {
            _importLogic = importLogic;
        }

        /// <summary>
        /// Import from id
        /// </summary>
        /// <param name="id"></param>
        /// <returns> IActionResult </returns>
        [HttpPost]
        public async Task<IActionResult> Import([FromBody]FileStream file, int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var import = await _importLogic.ImportToStudy(id, file);

            return Ok(import);
        }

    }
}

