//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using BDSA.ReviewIt.Server.Logic.StudyManager;
using Microsoft.AspNetCore.Mvc;

namespace Server.Controllers
{
    [Route("api/[controller]")]
    public class PublicationController : Controller
    {
        public readonly IPublicationLogic _PublicationLogic;

        public PublicationController(IPublicationLogic publicationLogic)
        {
            _PublicationLogic = publicationLogic;
        }

        /// <summary>
        /// Get all publications from study id
        /// </summary>
        /// <param name="studyId"></param>
        /// <returns> IActionResult </returns>
        [HttpGet("study/{studyId}")]
        public async Task<IActionResult> GetAllPublications(int studyId)
        {
            var getAll = await _PublicationLogic.GetAllForStudy(studyId);

            if (getAll == null)
            {
                return NotFound();
            }

            return Ok(getAll);
        }

        /// <summary>
        /// Get publication by id
        /// </summary>
        /// <param name="publicationId"></param>
        /// <returns> IActionResult </returns>
        [HttpGet("{publicationId}")]
        public async Task<IActionResult> GetPublicationById(int publicationId)
        {
            var get = await _PublicationLogic.GetById(publicationId);

            if (get == null)
            {
                return NotFound();
            }

            return Ok(get);
        }

    }
}

