//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using BDSA.ReviewIt.Server.Logic.StudyManager;
using Microsoft.AspNetCore.Mvc;
using ServerDTOs.ServerDTOs;

namespace Server.Controllers {
    [Route("api/[controller]")]
    public class StudyController : Controller {
        private readonly IStudyLogic _studyLogic;

        public StudyController(IStudyLogic studyLogic) {
            _studyLogic = studyLogic;
        }

        /// <summary>
        /// Get study from id
        /// </summary>
        /// <param name="id"></param>
        /// <returns> IActionResult </returns>
        [HttpGet("{id}")]
        public async Task<IActionResult> GetStudyById(int id) {
            var get = await _studyLogic.GetById(id);

            if (get == null) {
                return NotFound();
            }

            return Ok(get);
        }

        /// <summary>
        /// Create study
        /// </summary>
        /// <param name="study"></param>
        /// <returns> IActionResult </returns>
        [HttpPost]
        public async Task<IActionResult> CreateStudy([FromBody]StudyDTO study) {
            if (!ModelState.IsValid || study.Id != 0) {
                return BadRequest(ModelState);
            }

            var create = await _studyLogic.Create(study);

            return Ok(create);
        }

        /// <summary>
        /// Update study from id
        /// </summary>
        /// <param name="study"></param>
        /// <param name="id"></param>
        /// <returns> IActionResult </returns>
        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateStudy([FromBody]StudyDTO study, int id) {
            if (!ModelState.IsValid) {
                return BadRequest(ModelState);
            }

            var update = await _studyLogic.Update(study, id);

            if (update) {
                return NoContent();
            }

            return NotFound();
        }

        /// <summary>
        /// Delete study from id
        /// </summary>
        /// <param name="id"></param>
        /// <returns> IActionResult </returns>
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteStudy(int id) {
            var delete = await _studyLogic.Delete(id);

            if (delete) {
                return NoContent();
            }
            return NotFound();
        }

        /// <summary>
        /// Get all studies
        /// </summary>
        /// <param></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> GetAllStudies() {
            var getAll = await _studyLogic.GetAll();

            if (getAll == null) {
                return NotFound();
            }

            return Ok(getAll);
        }

    }
}

